name: Configure Lab Private Cloud
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: [self-hosted, terraform]

    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

      # vSphere / vRA / VCF environment-specific credentials
      TF_VAR_serviceAccountUserName: ${{ secrets.VCF_SERVICE_USER }}
      TF_VAR_serviceAccountPassword: ${{ secrets.VCF_SERVICE_PASSWORD }}
      TF_VAR_vcfa_refresh_token: ${{ secrets.VCFA_API_TOKEN}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: |
             terraform init -upgrade \
             -backend-config="conn_str=postgres://${{ secrets.PSQL_TF_USER }}:${{ secrets.PSQL_TF_PASS }}@${{ secrets.PSQL_TF_HOST }}:5433/${{ secrets.PSQL_TF_DB }}?sslmode=disable"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
              terraform plan -input=false -no-color \
              -var-file="envs/lab.tfvars" \
              -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve tfplan

      - name: Clean workspace
        run: rm -rf $GITHUB_WORKSPACE/.[!.]*

