name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: [self-hosted, terraform]

    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"

      # PostgreSQL backend (stored in GitHub Secrets)
      TF_VAR_backend_db_user: ${{ secrets.PSQL_TF_USER }}
      TF_VAR_backend_db_pass: ${{ secrets.PSQL_TF_PASS }}
      TF_VAR_backend_db_host: ${{ secrets.PSQL_TF_HOST }}
      TF_VAR_backend_db_name: ${{ secrets.PSQL_TF_DB }}

      # vSphere / vRA / VCF environment-specific credentials
      TF_VAR_serviceAccountUserName: ${{ secrets.VCF_SERVICE_USER }}
      TF_VAR_serviceAccountPassword: ${{ secrets.VCF_SERVICE_PASSWORD }}
      TF_VAR_vcfa_refresh_token: ${{ secrets.VCFA_API_TOKEN}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -var-file="envs/lab.tfvars"

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var-file="envs/lab.tfvars"
